# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.srcs/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/mb_block_hdmi_dino_controller_0_0.xci
# IP: The module: 'mb_block_hdmi_dino_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/src/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/src/clk_wiz_0/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: D:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.srcs/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/mb_block_hdmi_dino_controller_0_0.xci
# IP: The module: 'mb_block_hdmi_dino_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/src/hdmi_tx_0/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_dino_controller_0_0_1/src/clk_wiz_0/clk_wiz_0_ooc.xdc
