# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.srcs/sources_1/ip/dino_rom/dino_rom.xci
# IP: The module: 'dino_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/ip/dino_rom/dino_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dino_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.srcs/sources_1/ip/dino_rom/dino_rom.xci
# IP: The module: 'dino_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/U.I.U.C/FA24/ECE385/final_project/final_project/final_project.gen/sources_1/ip/dino_rom/dino_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dino_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
